title: Kashmir Latest News
description: Jammu & Kashmir Updates
baseurl: ""
url: "https://kashmirlatestnews.github.io"

theme: minima  # simple default theme (you can change later)

show_excerpts: true
