title: Kashmir Latest News
description: Jammu & Kashmir Updates

baseurl: ""
url: "https://kashmirlatestnews.github.io/"   # change to your Netlify URL

theme: minima

show_excerpts: true

plugins:
  - jekyll-feed
