title: Kashmir Latest News
description: Jammu and Kashmir Latest News Update 
baseurl: "" 
url: "https://kashmirlatestnews.github.io/"

theme: minima

show_excerpts: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
