title: Kashmir Latest News
description: Kashmir and jammu latest news update 
baseurl: "" 
url: "https://kashmirlatestnews.github.io/"

theme: minima

show_excerpts: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
